import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readdir, readlink, rename, rm, symlink, truncate, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { setTimeout as delay } from 'node:timers/promises';
import { canonicalJsonHash, createLooperCodexQueryService } from '../../../packages/loopers-codex/src/index.js';
import { createTestArtifact } from '../../../packages/loopers-codex/test/fixtures.js';
import { LOOPER_CODEX_CONSOLE_RELEASE, LooperCodexInputError, LooperCodexUnavailableError, createLooperCodexRuntime } from '../src/looper-codex-runtime.js';

const CAP = 128 * 1024 * 1024;
async function temp(run) { const root = await mkdtemp(join(tmpdir(), 'codex-runtime-')); try { return await run(root); } finally { await rm(root, { recursive:true, force:true }); } }
function bytesFor(a) { return Buffer.from(JSON.stringify(a) + '\n'); }
function releaseFor(bytes, artifact, extra={}) { return Object.freeze({ count:artifact?.semantic?.count ?? 3, artifactBytes:bytes.length, fileSha256:createHash('sha256').update(bytes).digest('hex'), artifactHash:artifact?.artifactHash ?? '0'.repeat(64), ...extra }); }
async function fixture(root, artifact=createTestArtifact()) { const artifactPath=join(root,'artifact.json'); const bytes=bytesFor(artifact); await writeFile(artifactPath,bytes); return {artifactPath, artifact, bytes, release:releaseFor(bytes,artifact)}; }
function loggerCapture(){const entries=[];return {entries,logger:{info(x){entries.push(x)},warn(x){entries.push(x)}}};}
async function waitForOpenDescriptor(target, timeoutMs=3000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){for(const name of await readdir('/proc/self/fd')){try{if(await readlink('/proc/self/fd/'+name)===target)return;}catch{}}await delay(1);}throw new Error('artifact descriptor was not observed');}
function frozen(x,seen=new Set()){if(!x||typeof x!=='object'||seen.has(x))return;seen.add(x);assert.ok(Object.isFrozen(x));for(const v of Object.values(x))frozen(v,seen);}
function walk(x, keys=[], strings=[], arrays=[]){if(typeof x==='string')strings.push(x);if(!x||typeof x!=='object')return {keys,strings,arrays};if(Array.isArray(x))arrays.push(x);for(const [k,v] of Object.entries(x)){keys.push(k);walk(v,keys,strings,arrays)}return {keys,strings,arrays};}

test('reviewed release descriptor is exact and frozen',()=>{assert.deepEqual(LOOPER_CODEX_CONSOLE_RELEASE,{count:7777,artifactBytes:60_203_971,fileSha256:'aa4f92f4e580f19691d591797826d750d45707ef0984a8b7e419d1e334813073',artifactHash:'5a776e6c2cacb211dedbbec7837416be46775f9e46a1a4cda4b3a96c70262f24'});assert.ok(Object.isFrozen(LOOPER_CODEX_CONSOLE_RELEASE));});

test('loads pinned artifact and exposes frozen status and foundation envelope',async()=>temp(async root=>{const f=await fixture(root);const runtime=await createLooperCodexRuntime({...f,expectedCount:3,logger:{}});const service=createLooperCodexQueryService(f.artifact,{expectedCount:3});assert.equal(runtime.available,true);assert.deepEqual(runtime.status,{available:true,schemaVersion:'1.0.0',artifactHash:f.artifact.artifactHash,codexVersion:f.artifact.semantic.versions.traitCodexVersion,count:3});assert.deepEqual(runtime.query('getTokenProfile',{tokenId:1}),service.getTokenProfile(1));frozen(runtime);frozen(runtime.query('getTokenProfile',{tokenId:1}));}));

test('absent artifact is not configured and methods throw typed unavailable errors',async()=>{const c=loggerCapture();const runtime=await createLooperCodexRuntime({logger:c.logger});assert.deepEqual(runtime.status,{available:false,reason:'not_configured'});assert.throws(()=>runtime.query('getCollectionSummary',{}),LooperCodexUnavailableError);assert.throws(()=>runtime.getProfileContext(1),LooperCodexUnavailableError);frozen(runtime);assert.deepEqual(c.entries,[{event:'looper_codex_unavailable',reason:'not_configured'}]);});

test('symlink and over-128MiB files are invalid',async()=>temp(async root=>{const f=await fixture(root);const link=join(root,'link.json');await symlink(f.artifactPath,link);assert.deepEqual((await createLooperCodexRuntime({artifactPath:link,release:f.release,expectedCount:3,logger:{}})).status,{available:false,reason:'invalid_artifact'});const big=join(root,'big.json');await writeFile(big,'');await truncate(big,CAP+1);assert.deepEqual((await createLooperCodexRuntime({artifactPath:big,release:Object.freeze({...f.release,artifactBytes:CAP+1}),expectedCount:3,logger:{}})).status,{available:false,reason:'invalid_artifact'});}));

test('SHA, byte count, semantic hash, malformed JSON and corrupt semantics fail closed',async()=>temp(async root=>{const f=await fixture(root);const cases=[{p:f.artifactPath,r:{...f.release,fileSha256:'f'.repeat(64)}},{p:f.artifactPath,r:{...f.release,artifactBytes:f.bytes.length+1}},{p:f.artifactPath,r:{...f.release,artifactHash:'e'.repeat(64)}}];const mp=join(root,'malformed');const mb=Buffer.from('{no');await writeFile(mp,mb);cases.push({p:mp,r:releaseFor(mb,null)});const bad=createTestArtifact();bad.semantic.traitStats[0].count++;bad.artifactHash=canonicalJsonHash(bad.semantic);const bp=join(root,'bad');const bb=bytesFor(bad);await writeFile(bp,bb);cases.push({p:bp,r:releaseFor(bb,bad)});for(const c of cases){const rt=await createLooperCodexRuntime({artifactPath:c.p,release:Object.freeze(c.r),expectedCount:3,logger:{}});assert.deepEqual(rt.status,{available:false,reason:'invalid_artifact'});assert.throws(()=>rt.query('getCollectionSummary',{}),LooperCodexUnavailableError);}}));

test('one pinned byte snapshot survives replacement of the configured path',async()=>temp(async root=>{const artifact=createTestArtifact();const artifactPath=join(root,'mutable.json');const bytes=Buffer.concat([bytesFor(artifact),Buffer.alloc(16*1024*1024,0x20)]);await writeFile(artifactPath,bytes);const pending=createLooperCodexRuntime({artifactPath,expectedCount:3,release:releaseFor(bytes,artifact),logger:{}});await waitForOpenDescriptor(artifactPath);await rename(artifactPath,join(root,'opened.json'));await writeFile(artifactPath,'{malformed replacement');const runtime=await pending;assert.equal(runtime.available,true);assert.equal(runtime.query('getTokenProfile',{tokenId:1}).result.identity.tokenId,1);}));

test('streaming cap rejects a file that grows after the initial stat',async()=>temp(async root=>{const artifact=createTestArtifact();const artifactPath=join(root,'growing.json');const bytes=Buffer.concat([bytesFor(artifact),Buffer.alloc(16*1024*1024,0x20)]);await writeFile(artifactPath,bytes);const capture=loggerCapture();const pending=createLooperCodexRuntime({artifactPath,expectedCount:3,release:releaseFor(bytes,artifact),logger:capture.logger});await waitForOpenDescriptor(artifactPath);await truncate(artifactPath,CAP+1);const runtime=await pending;assert.deepEqual(runtime.status,{available:false,reason:'invalid_artifact'});assert.equal(capture.entries[0].errorClass,'RangeError');}));

test('all seven closed schemas preserve envelopes and apply defaults',async()=>temp(async root=>{const f=await fixture(root);const rt=await createLooperCodexRuntime({...f,expectedCount:3,logger:{}});const s=createLooperCodexQueryService(f.artifact,{expectedCount:3});for(const [op,input,want] of [['getTokenProfile',{tokenId:1},s.getTokenProfile(1)],['explainTraits',{tokenId:1},s.explainTraits(1)],['compareTokens',{leftTokenId:1,rightTokenId:2},s.compareTokens(1,2)],['findByTraits',{filters:[{type:'Background',value:'Alpha'}]},s.findByTraits([{type:'Background',value:'Alpha'}],null,25)],['findByTraits',{filters:[{type:'Background',value:'Alpha'}],cursor:null,limit:1},s.findByTraits([{type:'Background',value:'Alpha'}],null,1)],['findSimilar',{tokenId:1},s.findSimilar(1,10)],['getTraitStats',{traitType:'Background',value:'Alpha'},s.getTraitStats('Background','Alpha')],['getCollectionSummary',{},s.getCollectionSummary()]])assert.deepEqual(rt.query(op,input),want,op);}));

test('unknown, non-plain, missing, extra and foundation-invalid input is typed',async()=>temp(async root=>{const f=await fixture(root);const rt=await createLooperCodexRuntime({...f,expectedCount:3,logger:{}});const cases=[['unknown',{}],['getTokenProfile',[]],['getTokenProfile',new Date()],['getTokenProfile',{}],['getTokenProfile',{tokenId:1,extra:true}],['explainTraits',{tokenId:1,extra:true}],['compareTokens',{leftTokenId:1}],['findByTraits',{filters:[],unexpected:true}],['findSimilar',{tokenId:1,limit:1,unexpected:true}],['getTraitStats',{traitType:'Background'}],['getCollectionSummary',{extra:true}],['getTokenProfile',{tokenId:0}],['compareTokens',{leftTokenId:1,rightTokenId:1}],['findByTraits',{filters:[{type:'Background',value:'Alpha',extra:true}]}],['findSimilar',{tokenId:1,limit:26}],['findSimilar',{tokenId:1,limit:null}],['findByTraits',{filters:[{type:'Background',value:'Alpha'}],limit:null}],['getTraitStats',{traitType:'Unknown',value:'Unknown'}]];for(const [op,input] of cases)assert.throws(()=>rt.query(op,input),LooperCodexInputError,op);assert.throws(()=>rt.query('getCollectionSummary',{extra:true}),/unknown/i);}));

test('prompt projection is frozen, bounded, and excludes sensitive or operational keys',async()=>temp(async root=>{const f=await fixture(root);const rt=await createLooperCodexRuntime({...f,expectedCount:3,logger:{}});const x=rt.getProfileContext(1);assert.deepEqual(Object.keys(x),['schemaVersion','artifactHash','codexVersion','identity','interpretation','traits','versions','evidence']);assert.deepEqual(Object.keys(x.identity),['tokenId','canonicalName']);assert.deepEqual(Object.keys(x.interpretation),['primaryClass','secondaryClass','specialization','risk','autonomy','voice','values','communicationStyle','humor','origin','shortLore','missionBias','firstMission','recommendedSkills']);assert.ok(x.interpretation.recommendedSkills.every(v=>v.status==='recommended'));const w=walk(x);assert.equal(w.keys.some(k=>['owner','source','path','enabled'].includes(k.toLowerCase())),false);assert.ok(w.strings.every(v=>v.length<=512));assert.ok(w.arrays.every(v=>v.length<=16));frozen(x);}));

test('logs only one safe ready event or bounded unavailable diagnostic',async()=>temp(async root=>{const f=await fixture(root);const ok=loggerCapture();await createLooperCodexRuntime({...f,expectedCount:3,logger:ok.logger});assert.equal(ok.entries.length,1);assert.deepEqual(Object.keys(ok.entries[0]),['event','schemaVersion','artifactHashPrefix','count','loadMs','rssDeltaBytes']);assert.equal(ok.entries[0].artifactHashPrefix,f.artifact.artifactHash.slice(0,12));assert.ok(Number.isFinite(ok.entries[0].loadMs));assert.ok(Number.isSafeInteger(ok.entries[0].rssDeltaBytes));assert.equal(JSON.stringify(ok.entries).includes(root),false);const no=loggerCapture();await createLooperCodexRuntime({...f,expectedCount:3,release:Object.freeze({...f.release,fileSha256:'0'.repeat(64)}),logger:no.logger});assert.equal(no.entries.length,1);assert.deepEqual(Object.keys(no.entries[0]),['event','reason','errorClass']);assert.equal(JSON.stringify(no.entries).includes(root),false);}));
